 - name: Add Public SSH Key standalone
   copy: src=../files/id_rsa dest=/root/.ssh/id_rsa owner=root group=root mode=0400
   tags: bootstrap

 - name: Add Private SSH Key standalone
   copy: src=../files/id_rsa.pub dest=/root/.ssh/id_rsa.pub owner=root group=root mode=0400
   tags: bootstrap

 - name: Add all public key files in role/files/sshkeys/
   authorized_key: user=root key="{{ lookup('file', '{{ item }}') }}"
   with_fileglob:
     - ../../../files/sshkeys/*
   tags: bootstrap
