- name: Create work dir
  file: path=/var/mesos state=directory
  tags: deploy

- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/
  tags: deploy

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk
  tags: deploy

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/
  tags: deploy

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/
  tags: deploy

- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  tags: deploy
  notify:
    - Restart mesos

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  tags: deploy
  notify:
    - Restart mesos

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  tags: deploy
  notify:
    - Restart mesos

- name: Mesos master script
  template: src=init-mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  tags: deploy
  notify:
    - Restart mesos

- name: Mesos slave script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  tags: deploy
  notify:
    - Restart mesos

- name: Ensure starting mesos-salve service on Slave node
  service: name=mesos-slave state=reloaded
  when: mesos_install_mode == "slave"
  tags: deploy

- name: Ensure starting mesos-master service on Master node
  service: name=mesos-master state=reloaded
  when: mesos_install_mode == "master"
  tags: deploy

- name: Ensure stoping mesos-salve service on Master node
  service: name=mesos-slave state=stopped
  when: mesos_install_mode == "master"
  tags: deploy

- name: Ensure stoping mesos-master service on Slave node
  service: name=mesos-master state=stopped
  when: mesos_install_mode == "slave"
  tags: deploy

- name: Ensure stoping zookeeper service on Slave node
  service: name=zookeeper state=stopped
  when: mesos_install_mode == "slave"
  tags: deploy
