- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present
  tags: provision

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present
  tags: provision

- name: Install main ubuntu OS packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
  tags: provision

- name: Install Mesos package
  apt: pkg={{item}} state=present force=yes
  with_items:
    - mesos={{mesos_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
  tags: provision
