- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws-env

  tasks:
    - local_action: wait_for port=22 host="{{ stack.stack_outputs.MainInstance }}" search_regex=OpenSSH delay=10
      tags: bootstrap

    - action: shell ssh -i {{ stack_key_ssh_ec2 }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no centos@{{ stack.stack_outputs.MainInstance }} "echo success"
      register: root_enabled
      until: root_enabled.stdout.find("success") != -1
      retries: 5
      delay: 60
      tags: bootstrap

    - action: shell ssh -i {{ stack_key_ssh_ec2 }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no centos@{{ stack.stack_outputs.MainInstance }} 'sudo yum -y install python-simplejson; sleep 5'
      tags: bootstrap
